### ISSUE TITLE
On my iPhone, when I am logged in, I see lunch options

### ISSUE THREAD

**Issue by ultrasaurus** [all-the-hubbub/hubbub#7]
As an admin, I can modify data in the Firebase Console, then the app shows list of lunch options.

When this story is complete, add details about what the database schema is to the README (or linked md file), and then write the story for web app and link to that

**Comment by justinrosenthal** [comment]
Schema: https://github.com/all-the-hubbub/hubbub/blob/1d497275a512435c61a5231bbe9082f3d905b862/doc/database.md

Web story: #31
