### ISSUE TITLE
home page copy

### ISSUE THREAD

**Issue by ultrasaurus** [all-the-hubbub/hubbub#75]
There's some copy on the temp landing page which might be useful https://www.hubbub.live/ but we really need something that explains what the app does...

needs links to iOS, Android and Web login

@brendanlim is working on this

WIP:
![image](https://cloud.githubusercontent.com/assets/41906/26124023/d5680ea0-3a31-11e7-9130-8e968cb98692.png)

**Comment by brendanlim** [comment]
<img width="481" alt="screen shot 2017-05-16 at 4 11 56 pm" src="https://cloud.githubusercontent.com/assets/1788/26132053/74319c98-3a52-11e7-85af-856db5d599de.png">

<img width="1130" alt="screen shot 2017-05-16 at 4 12 48 pm" src="https://cloud.githubusercontent.com/assets/1788/26132067/87e18212-3a52-11e7-9c4d-82e060b32bc2.png">
